on: 
  schedule: 
    - cron: '0 14 * * 2'
  workflow_dispatch: 

name: 'databases/postgresql/load-your-postgresql-database-with-data/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          export REGION=southcentralus
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $POSTGRESQL_NAME ]]; then
          export POSTGRESQL_NAME=postgresql-$RANDOM
          export POSTGRESQL_USERNAME=postgresql
          export POSTGRESQL_PASSWORD=p#ssw0rd-$RANDOM
          fi
          
          az postgres server create \
          --admin-user $POSTGRESQL_USERNAME \
          --admin-password $POSTGRESQL_PASSWORD \
          --name $POSTGRESQL_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku B_Gen5_1 \
          --ssl-enforcement Disabled
          export LOCAL_IP=`curl -s whatismyip.akamai.com`
          
          az postgres server firewall-rule create \
          --resource-group $RESOURCE_GROUP \
          --server $POSTGRESQL_NAME \
          --name AllowMyLocalIP \
          --start-ip-address $LOCAL_IP \
          --end-ip-address $LOCAL_IP
          
          cd databases/postgresql/load-your-postgresql-database-with-data
          
          export POSTGRESQL_DNS_NAME=`az postgres server show \
          --resource-group $RESOURCE_GROUP \
          --name $POSTGRESQL_NAME \
          --query fullyQualifiedDomainName \
          --output tsv`
          
          export POSTGRESQL_CLIENT_USERNAME="$POSTGRESQL_USERNAME@$POSTGRESQL_NAME"
          
          PGPASSWORD=$POSTGRESQL_PASSWORD psql --host=$POSTGRESQL_DNS_NAME --port=5432 --username $POSTGRESQL_CLIENT_USERNAME --dbname=postgres --file load.sql
          
          cd ../../..
          
          
          echo 'SELECT COUNT(*) FROM countries;' > check.sql
          export RESULT=$(PGPASSWORD=$POSTGRESQL_PASSWORD psql --host=$POSTGRESQL_DNS_NAME -qtAX --port=5432 --username $POSTGRESQL_CLIENT_USERNAME --dbname=demo --csv < check.sql)
          if [[ "$RESULT" != "1" ]]; then
          echo "PostgreSQL data was NOT loaded"
          exit 1
          fi
          az group delete --name $RESOURCE_GROUP --yes || true