on: 
  workflow_dispatch: 

name: 'kusto/create-table/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $REGION ]]; then
          export REGION=northcentralus
          echo "Using 'northcentralus' region"
          fi
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          az extension add -n kusto
          
          if [[ -z $ADX_CLUSTER_NAME ]]; then
          export ADX_CLUSTER_NAME=adxcluster$RANDOM
          az kusto cluster create \
          --cluster-name $ADX_CLUSTER_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku name="Standard_D13_v2" tier="Standard" \
          --location $REGION \
          --type SystemAssigned
          fi
          
          
          if [[ -z $ADX_DATABASE_NAME ]]; then
          export ADX_DATABASE_NAME=adxdb$RANDOM
          az kusto database create \
          --cluster-name $ADX_CLUSTER_NAME \
          --resource-group "$RESOURCE_GROUP" \
          --database-name "$ADX_DATABASE_NAME" \
          --read-write-database location="$REGION"
          fi
          
          export ADX_TABLE=Events