on: 
  workflow_dispatch: 

name: 'mssql/load-your-mssql-database-with-data/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          export MSSQL_NAME=mssql-$RANDOM
          export MSSQL_USERNAME=mssql
          export MSSQL_PASSWORD=p#ssw0rd-$RANDOM
          if [[ -z $MSSQL_NAME ]]; then
          export MSSQL_NAME=mssql-$RANDOM
          export MSSQL_USERNAME=mssql
          export MSSQL_PASSWORD=p#ssw0rd-$RANDOM
          fi
          az sql server create \
          --admin-user $MSSQL_USERNAME \
          --admin-password $MSSQL_PASSWORD \
          --name $MSSQL_NAME \
          --resource-group $RESOURCE_GROUP
          export LOCAL_IP=`curl -s whatismyip.akamai.com`
          
          az sql server firewall-rule create \
          --resource-group $RESOURCE_GROUP \
          --server $MSSQL_NAME \
          --name AllowMyLocalIP \
          --start-ip-address $LOCAL_IP \
          --end-ip-address $LOCAL_IP
          
          cd mssql/load-your-mssql-database-with-data
          
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
          sudo apt-get update
          sudo apt-get install mssql-cli
          sudo apt-get install -f
          
          export MSSQL_DNS_NAME=`az sql server show \
          --resource-group $RESOURCE_GROUP \
          --name $MSSQL_NAME \
          --query fullyQualifiedDomainName \
          --output tsv`
          
          export MSSQL_CLIENT_USERNAME="$MSSQL_USERNAME@$MSSQL_NAME"
          
          mssql-cli -S $MSSQL_DNS_NAME -U $MSSQL_CLIENT_USERNAME -P $MSSQL_PASSWORD -i create.sql
          
          mssql-cli -S $MSSQL_DNS_NAME -U $MSSQL_CLIENT_USERNAME -P $MSSQL_PASSWORD -d demo -i load.sql
          
          cd ../..
          
          
          az group delete --name $RESOURCE_GROUP --yes || true