on: 
  schedule: 
    - cron: '0 21 * * 1'
  workflow_dispatch: 

name: 'postgres/get-country/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v3'
      - run: |
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joaz-rg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $POSTGRESQL_NAME ]]; then
          export POSTGRESQL_NAME=postgresql-$RANDOM
          export POSTGRESQL_USERNAME=postgresql
          export POSTGRESQL_PASSWORD=p#ssw0rd-$RANDOM
          fi
          
          az postgres server create \
          --admin-user $POSTGRESQL_USERNAME \
          --admin-password $POSTGRESQL_PASSWORD \
          --name $POSTGRESQL_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku B_Gen5_1 \
          --ssl-enforcement Disabled
          export LOCAL_IP=`curl -s whatismyip.akamai.com`
          
          az postgres server firewall-rule create \
          --resource-group $RESOURCE_GROUP \
          --server-name $POSTGRESQL_NAME \
          --name AllowMyLocalIP \
          --start-ip-address $LOCAL_IP \
          --end-ip-address $LOCAL_IP
          
          cd postgres/load-your-postgresql-database-with-data
          
          export POSTGRESQL_DNS_NAME=`az postgres server show \
          --resource-group $RESOURCE_GROUP \
          --name $POSTGRESQL_NAME \
          --query fullyQualifiedDomainName \
          --output tsv`
          
          export POSTGRESQL_CLIENT_USERNAME="$POSTGRESQL_USERNAME@$POSTGRESQL_NAME"
          
          PGPASSWORD=$POSTGRESQL_PASSWORD psql --host=$POSTGRESQL_DNS_NAME --port=5432 --username $POSTGRESQL_CLIENT_USERNAME --dbname=postgres --file load.sql
          
          cd ../..
          
          
          cd postgres/get-country
          
          mvn package
          java -jar target/get-country.jar jdbc:postgresql://$POSTGRESQL_DNS_NAME:5432/demo?ssl=true\&sslmode=require $POSTGRESQL_CLIENT_USERNAME $POSTGRESQL_PASSWORD USA
          
          cd ../..
          
          
          cd postgres/get-country
          export RESULT=$(java -jar target/get-country.jar jdbc:postgresql://$POSTGRESQL_DNS_NAME:5432/demo?ssl=true\&sslmode=require $POSTGRESQL_CLIENT_USERNAME $POSTGRESQL_PASSWORD USA)
          cd ../..
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != *"United States"* ]]; then
          echo "Unable to get the correct country information"
          exit 1
          fi