on: 
  schedule: 
    - cron: '0 2 * * 3'
  workflow_dispatch: 

name: 'spring/helloworld/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v3'
      - run: |
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=joaz-rg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          az extension add --name spring
          
          export SPRING_NAME=spring-$RANDOM
          
          az spring create \
          --resource-group $RESOURCE_GROUP \
          --name $SPRING_NAME
          
          cd spring/helloworld
          
          mvn package
          az spring app create \
          --name helloworld \
          --service ${SPRING_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --assign-endpoint \
          --runtime-version Java_11 \
          --verbose
          
          az spring app deploy \
          --name helloworld \
          --service ${SPRING_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --artifact-path ./target/spring-helloworld.jar \
          --verbose
          
          az spring app show \
          --name helloworld \
          --service ${SPRING_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --query properties.url \
          --output tsv
          
          export URL=$(az spring app show \
          --name helloworld \
          --service ${SPRING_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --query properties.url \
          --output tsv)
          export RESULT=$(curl $URL)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != *"Hello World"* ]]; then
          echo "Response did not contain 'Hello World'"
          exit 1
          fi